services:
  test-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: totally_safe_password
      MYSQL_USER: test_user
      MYSQL_PASSWORD: bad_password_practices
      MYSQL_DATABASE: dbmate_demo
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  dbmate-up:
    image: amacneil/dbmate
    restart: on-failure
    depends_on:
      - test-db
    environment:
      DATABASE_URL: "mysql://root:password@test-db:3306/dbmate_demo"
    volumes:
      - ./db/migrations:/db/migrations
    entrypoint: ["dbmate", "up"]

  dbmate-up-circle:
    image: amacneil/dbmate
    restart: on-failure
    environment:
      DATABASE_URL: "mysql://test_user:bad_password_practices@${SQL_DOCKER_NAME}:3306/dbmate_demo"
    volumes:
      - ./db/migrations:/db/migrations
    entrypoint: [ "dbmate", "up" ]

volumes:
  mysql-data:
