version: 2.1
orbs:
  path-filtering: circleci/path-filtering@1

setup: true

parameters:
  run-build-and-deploy:
    type: boolean
    default: false

workflows:
  always-run:
    jobs:
      - path-filtering/filter:
          name: check updated files
          mapping: |
            src/*.js run-build-and-deploy true
            ./Dockerfile run-build-and-deploy true
          base-revision: main
