version: 2.1
orbs:
  path-filtering: circleci/path-filtering@1

setup: true

workflows:
  always-run:
    jobs:
      - path-filtering/filter:
          name: check updated files
          mapping: |
            src/*.js run-build-and-deploy true
            ./Dockerfile run-build-and-deploy true
            .circleci/config.yml run-build-and-deploy true
            .circleci/continue_config.yml run-build-and-deploy true
          base-revision: main
