version: 2.1
orbs:
  node: circleci/node@7.2.1
  aws-ecr: circleci/aws-ecr@9.7.0
  aws-cli: circleci/aws-cli@5.4.1
  aws-ecs: circleci/aws-ecs@7.1.0

jobs:
  test:
    docker:
      - image: cimg/node:25.1.0
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: dbmate_demo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: NPM Install
          command: npm install
      - run:
          name: Wait for MySQL to be ready
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: Run Docker Compose
          command: docker compose up -d test-db dbmate-up --remove-orphans
      - run:
          name: Docker PS
          command: docker ps
      - run:
          name: Run Tests
          command: npm run test-circle


workflows:
  build_and_deploy:
    jobs:
      - test
