version: 2.1
orbs:
  node: circleci/node@7.2.1
  aws-ecr: circleci/aws-ecr@9.7.0
  aws-cli: circleci/aws-cli@5.4.1
  aws-ecs: circleci/aws-ecs@7.1.0

jobs:
  test:
    docker:
      - image: cimg/node:25.1.0
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: dbmate_demo
          MYSQL_USER: test_user
          MYSQL_PASSWORD: bad_password_practices
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: NPM Install
          command: npm install
      - run:
          name: Wait for MySQL to be ready
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: Docker PS
          command: |
            #!/bin/bash
            
            SQL_DOCKER_NAME=$(docker ps | grep "cimg/mysql" | awk '{print $10}')
            
            echo SQL_DOCKER_NAME=${SQL_DOCKER_NAME} > .env
            
            npx dbmate up --migrations-dir "./db/migrations/" --url "mysql://test_user:bad_password_practices@${SQL_DOCKER_NAME}:3306/dbmate_demo"
      - run:
          name: Apply DB Migrations
          command: docker compose up -d dbmate-up-circle --remove-orphans
      - run:
          name: Run Tests
          command: npm run test-circle


workflows:
  build_and_deploy:
    jobs:
      - test
