version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@9.7.0
  aws-cli: circleci/aws-cli@5.4.0
  aws-ecs: circleci/aws-ecs@7.1.0

parameters:
  run-build-and-deploy:
    type: boolean
    default: false

jobs:
  test:
    docker:
      - image: cimg/node:25.1.0
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: dbmate_demo
          MYSQL_USER: test_user
          MYSQL_PASSWORD: bad_password_practices
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: NPM Install
          command: npm install
      - run:
          name: Wait for MySQL to be ready
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: Set Docker Compose ENV
          command: echo "DATABASE_URL=mysql://test_user:bad_password_practices@localhost:3306/dbmate_demo" >> .env
      - run:
          name: Apply DB Migrations
          command: npx dbmate up
      - run:
          name: Run Tests
          command: npm run test-circle

workflows:
  run-tests:
    jobs:
      - test

  build_and_deploy:
    when: << pipeline.parameters.run-build-and-deploy >>
    requires:
      run-tests
    jobs:
      - aws-ecr/build_and_push_image:
          account_id: ${AWS_ACCOUNT_ID}
          auth:
            - aws-cli/setup:
                profile_name: OIDC-USER
                role_arn: ${IAM_ARN}
          profile_name: OIDC-USER
          repo: test
          tag: ${CIRCLE_SHA1}
          region: us-east-1
          filters:
            branches:
              only: main

      - aws-ecs/deploy_service_update:
          auth:
            - aws-cli/setup:
                profile_name: OIDC-USER
                role_arn: ${IAM_ARN}
          cluster: test-cluster
          family: test-service
          service_name: test-service
          profile_name: OIDC-USER
          region: us-east-1
          requires:
            - aws-ecr/build_and_push_image
          filters:
            branches:
              only: main
